language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - python -m unittest discover
after_success:
  - codecov --token=c5fbcba0-291c-465a-9959-1f1e33399fb1