language: python
python:
  - "2.7"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - python -m unittest discover --cov=codecov
after_success:
  - codecov