language: python
python:
  - "2.7"
notifications:
  email: false
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
  - pip install coverage
# command to run tests
script:
  - bash <(coverage run -m unittest discover)
  # - python -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash) -t c5fbcba0-291c-465a-9959-1f1e33399fb1
  # - codecov --token=c5fbcba0-291c-465a-9959-1f1e33399fb1
