language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r docs/requirements.txt
# command to run tests
script:
  - python -m unittest discover
  - python coverage run tests/npdb_tests/core_tests/test_dbarray.py
after_success:
  - codecov